name: Deploy Nuxt App

on:
  push:
    branches:
      - production # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19.9.0 # Match your Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build Nuxt App
      run: npm run build

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY  }}
        script: |
          cd /var/www/html/stitchit-front
          git pull origin production
          npm install
          npm run build
          pm2 restart nuxt || pm2 start npm --name "nuxt" -- start
